// Generated by ADead-BIB CUDA Backend
// ADead-BIB + CUDA = Assembly Moderno con GPU Power

#include <stdio.h>
#include <cuda_runtime.h>

__global__ void vectorAdd(float *A, float *B, float *C, int n) {

    int i = blockDim.x * blockIdx.x + threadIdx.x;
    if (i < n) {
        C[i] = A[i] + B[i];
    }
}


// Host launcher for vectorAdd
int main() {
    int n = 10000;
    size_t size = n * sizeof(float);
    
    // Allocate host memory
    float *h_A = (float*)malloc(size);
    float *h_B = (float*)malloc(size);
    float *h_C = (float*)malloc(size);
    
    // Initialize
    for (int i = 0; i < n; i++) {
        h_A[i] = (float)i;
        h_B[i] = (float)i * 2;
    }
    
    // Allocate device memory
    float *d_A, *d_B, *d_C;
    cudaMalloc(&d_A, size);
    cudaMalloc(&d_B, size);
    cudaMalloc(&d_C, size);
    
    // Copy to device
    cudaMemcpy(d_A, h_A, size, cudaMemcpyHostToDevice);
    cudaMemcpy(d_B, h_B, size, cudaMemcpyHostToDevice);
    
    // Launch kernel
    int threadsPerBlock = 256;
    int blocksPerGrid = (n + threadsPerBlock - 1) / threadsPerBlock;
    printf("ADead-BIB + CUDA: Launching %s with %d blocks of %d threads\\n", 
           "vectorAdd", blocksPerGrid, threadsPerBlock);
    
    vectorAdd<<<blocksPerGrid, threadsPerBlock>>>(d_A, d_B, d_C, n);
    
    // Copy result back
    cudaMemcpy(h_C, d_C, size, cudaMemcpyDeviceToHost);
    
    // Verify
    printf("Result: C[0] = %.2f, C[1] = %.2f, C[%d] = %.2f\\n", 
           h_C[0], h_C[1], n-1, h_C[n-1]);
    
    // Cleanup
    cudaFree(d_A);
    cudaFree(d_B);
    cudaFree(d_C);
    free(h_A);
    free(h_B);
    free(h_C);
    
    printf("ADead-BIB + CUDA: Test PASSED!\\n");
    return 0;
}
